config/routes.rb
Rails.application.routes.draw do

  resources :results , :except => [:show]
  resources :information
  resources :tickets
  resources :timecards
  resources :admin

  post '/come' => 'timecards#come'
  post '/out' => 'timecards#out'

  root to: 'home#index'
  get '/logout' => 'sessions#destroy'



  devise_for :users, controllers: {
   omniauth_callbacks: "users/omniauth_callbacks"
 }
  resources :users, :only => [:index, :show, :edit, :update ]

  resources :users do
    resources :results
  end

  resources :users do
    resources :timecards
  end

  resources :information do
    resources :tickets
  end
end

app/models/grade.rb
class Grade < ActiveHash::Base
  self.data = [
    {code: 'ELEMENTARY_1', name: '小１', next_grade_code: 'ELEMENTARY_2'},
    {code: 'ELEMENTARY_2', name: '小２', next_grade_code: 'ELEMENTARY_3'},
    {code: 'ELEMENTARY_3', name: '小３', next_grade_code: 'ELEMENTARY_4'},
    {code: 'ELEMENTARY_4', name: '小４', next_grade_code: 'ELEMENTARY_5'},
    {code: 'ELEMENTARY_5', name: '小５', next_grade_code: 'ELEMENTARY_6'},
    {code: 'ELEMENTARY_6', name: '小６', next_grade_code: 'JUNIOR_HIGH_1'},
    {code: 'JUNIOR_HIGH_1', name: '中１', next_grade_code: 'JUNIOR_HIGH_2'},
    {code: 'JUNIOR_HIGH_2', name: '中２', next_grade_code: 'JUNIOR_HIGH_3'},
    {code: 'JUNIOR_HIGH_3', name: '中３', next_grade_code: 'HIGH_1'},
    {code: 'HIGH_1', name: '高１', next_grade_code: 'HIGH_2'},
    {code: 'HIGH_2', name: '高２', next_grade_code: 'HIGH_3'},
    {code: 'HIGH_3', name: '高３', next_grade_code: 'GRADUATED'},
    {code: 'GRADUATED', name: '卒業生', next_grade_code: 'GRADUATED'}
  ]
end

app/models/information.rb
class Information < ActiveRecord::Base
  belongs_to :user
  has_many :tickets, :dependent => :delete_all
  validates :title, length: { maximum: 50 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_date, presence: true
  validates :expire_date, presence: true
  validate :validate_start_date
  validate :validate_expire_date

  paginates_per 10

  private
  def validate_start_date
    if start_date <= Time.now
      errors.add(:start_date ,'は現在時刻以降の値を設定してください')
    end
  end

  def validate_expire_date
    if expire_date >= start_date
      errors.add(:expire_date ,'は開催日時以前の値を設定してください')
    end
  end
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :user
  belongs_to :author, class_name: User
  validates :title, length: { maximum: 50 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :author_id, presence: true

  paginates_per 10

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :information
  validates :comment,length: { maximum: 30}, allow_blank: true
  validates :comment2,length: { maximum: 30}, allow_blank: true
end

app/models/timecard.rb
class Timecard < ActiveRecord::Base
  COMING_TITLE = '登校時刻'.freeze
  OUT_TITLE = '下校時刻'.freeze

  belongs_to :user

  validates :title, inclusion: { in: [COMING_TITLE, OUT_TITLE] }

  def coming?
    title == COMING_TITLE
  end

  def out?
    title == OUT_TITLE
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :results, :dependent => :delete_all
  has_many :report_results, :class_name => Result, :foreign_key => :author_id
  has_many :tickets, :dependent => :delete_all
  has_many :timecards, :dependent => :delete_all
  has_many :information
  has_many :participating_events, through: :tickets, source: :information

  paginates_per 10

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first

    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  def recent_timecard
    timecards.order(created_at: :desc).first
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, except: [:show]

  def index
    @user = User.page(params[:page])
  end

  def show
    if current_user.admin?
      @user = User.find(params[:id])
      @result = @user.results
    else
      @user = current_user
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def index
    @info = Information.page(params[:page]).order('created_at DESC')
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmed_user
  before_action :admin_user, except: [:index]
  def new
    @user = User.find(params[:format])
    @result = @user.results.new
  end

  def create
    @user = User.find(params[:user_id])
    @result = @user.results.create(result_params)
    @result.author = current_user
    if @result.save
      redirect_to result_path(@user), notice: '指導報告を作成しました。'
    else
      render :new
    end
  end

  def index
    if current_user.admin?
      @results = Result.page(params[:page]).order('created_at DESC')
      if params[:user_id]
        @results = @results.where(user_id: params[:user_id])
      end
    else
      @user = current_user
      @results = @user.results.page(params[:page]).order('created_at DESC')
    end
  end

  def edit
    @result = Result.find(params[:id])
    @user = @result.user
  end

  def update
    @result = Result.find(params[:id])
    @result.update(result_params)
    if @result.save
      redirect_to result_path(@result.user), notice: '指導報告を修正しました。'
    else
      render :edit
    end
  end

  def destroy
    @result = Result.find(params[:id])
    @result.destroy!
    redirect_to result_path(@result.user)
  end



  private

  def result_params
    params.require(:result).permit(
      :title, :content
      )
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirmed_user
  before_action :admin_user, except: [:create,:destroy,:new,:show]

  PER = 5

  def index
    @info = Information.find(params[:information_id])
    @tickets = @info.tickets.page(params[:page]).per(PER).all.order('created_at DESC')
  end
  def new
    raise ApplicationController::RoutingError,'申し訳ありません、ログインしてからお申し込みください。'
  end

  def create
    ticket = current_user.tickets.build do |t|
      t.information_id = params[:information_id]
      t.comment = params[:ticket][:comment]
    end
    if ticket.save
      flash[:notice] = '参加登録しました'
      head 201
    else
      render json: {messages: ticket.errors.full_messages},status: 422
    end
  end

  def show
    from = Time.now.at_beginning_of_day - 30.day
    to = from + 60.day
    @tickets = current_user.tickets.where(created_at: from...to).order(created_at: :desc)
  end

  def destroy
    ticket = current_user.tickets.find_by!(information_id: params['information_id'])
    ticket.destroy!
    redirect_to root_path,notice: 'イベントへの参加をキャンセルしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :confirmed_user
before_action :admin_user, except: [:show]
  def show
    if current_user.admin?
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_index_path, notice: '生徒情報を更新しました'
    else
      redirect_to user_path , notice: 'ログインしてください'
    end
  end

  def destroy

  end
  private

  def user_params
    params.require(:user).permit(
      :name, :grade_code, :school_name, :phone_number, :confirmed
    )
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(*controllers_name)
    "active" if controllers_name.include?(params[:controller])
  end
  def registered_tickets
    now = Time.zone.now
    current_user.participating_events.where(':now < start_date', now: now).count if current_user.participating_events
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timecards_helper.rb
module TimecardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.slim
h1
  | 生徒管理
= paginate @user
.table-responsive
  table.table.table-hover
    tbody
      tr
        td
          | 氏名
        td
        td
        td
        td
    - @user.each do |user|
      - if user.confirmed? && user.admin? == false
        tr
          td
            = user.name
          td
            = link_to '登録内容確認' , user_path(user), class:'btn btn-warning btn-sm'
          td
            = link_to '登録内容更新' , edit_user_path(user), class:'btn btn-danger btn-sm'
          td
            = link_to '指導情報登録',new_result_path(user), class:'btn btn-primary btn-sm'
          td
            = link_to '過去の指導情報',result_path(user), class:'btn btn-info btn-sm'

app/views/layouts/_navigation.html.slim
header.navbar.navbar-default[role="navigation"]
  .container
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbarcommit"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'テストアプリ', root_path, class: 'navbar-brand'
    #navbarcommit.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user && current_user.admin?
          li.navbar-text.text-muted
            = current_user.name + '(管理者)'
          li
            = link_to 'お知らせ作成', new_information_path
          li
            = link_to '管理画面', admin_index_path
        - elsif current_user
          li.navbar-text.text-muted
            = current_user.name
        - if current_user
          - if current_user.recent_timecard.nil? || current_user.recent_timecard.out?
            = form_for current_user.timecards.build, html:{class: 'navbar-form navbar-left'}, url: {controller: :timecards, action: :come} do |f|
              = f.hidden_field :title, value: Timecard::COMING_TITLE, class:'form-group'
              = f.button '登校', class: 'btn btn-default', data: {disable_with:'処理中です....'}
          - if current_user.recent_timecard.nil? || current_user.recent_timecard.coming?
            = form_for current_user.timecards.build, html:{class: 'navbar-form navbar-left'}, url: {controller:  :timecards, action: :out} do |f|
              = f.hidden_field :title, value: Timecard::OUT_TITLE, class:'form-group'
              = f.button '下校', class: 'btn btn-default', data: {disable_with:'処理中です....'}
          li
            = link_to 'ログアウト', logout_path
        - else
          li
            = link_to 'Googleでサインイン', user_google_oauth2_omniauth_authorize_path

app/views/layouts/_sidebar.html.slim
p.text-muted
  i.zmdi.zmdi-account.zmdi-hc-3x
  |      
  = current_user.name
ul.nav.nav-pills.nav-stacked
  li class=(active?('home','information'))
    = link_to root_path do
      i.zmdi.zmdi-info-outline.zmdi-hc-2x
      |　お知らせ
  li class=(active?('results'))
    = link_to results_path do
      i.zmdi.zmdi-file-text.zmdi-hc-2x
      |　指導報告
  li class=(active?('tickets'))
    = link_to ticket_path(current_user) do
      i.zmdi.zmdi-edit.zmdi-hc-2x
      |　申込中イベント
      span.badge
        = registered_tickets
  li class=(active?('timecards'))
    = link_to timecard_path(current_user) do
      i.zmdi.zmdi-alarm.zmdi-hc-2x
      |　登下校時間
  li class=(active?('users'))
    = link_to  user_path(current_user) do
      i.zmdi.zmdi-lock-outline.zmdi-hc-2x.text-center
      |　登録情報

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) : '塾アプリ'
    meta[charset="utf-8"]
    link[rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"]
    link[rel="stylesheet" href="https://code.getmdl.io/1.1.2/material.light_blue-yellow.min.css"]
    script[defer src="https://code.getmdl.io/1.1.1/material.min.js"]
    link[rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/navigation'
    main.container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      - if current_user
        .row
          .col-md-4
            = render 'layouts/sidebar'
          .col-md-8
            = yield
      - else
        .col-md-12
          = yield