config/routes.rb
Rails.application.routes.draw do

  resources :results , :except => [:show]
  resources :information
  resources :tickets
  resources :timecards
  resources :admin

  post '/come' => 'timecards#come'
  post '/out' => 'timecards#out'

  root to: 'home#index'
  get '/logout' => 'sessions#destroy'



  devise_for :users, controllers: {
   omniauth_callbacks: "users/omniauth_callbacks"
 }
  resources :users, :only => [:index, :show, :edit, :update ]

  resources :users do
    resources :results
  end

  resources :users do
    resources :timecards
  end

  resources :information do
    resources :tickets
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :results, :dependent => :delete_all
  has_many :report_results, :class_name => Result, :foreign_key => :author_id
  has_many :tickets, :dependent => :delete_all
  has_many :timecards, :dependent => :delete_all
  has_many :information
  has_many :participating_events, through: :tickets, source: :information

  paginates_per 10

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first

    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
    user
  end

  def recent_timecard
    timecards.order(created_at: :desc).first
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = 'ログインしました'
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :confirmed_user
before_action :admin_user, except: [:show]
  def show
    if current_user.admin?
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_index_path, notice: '生徒情報を更新しました'
    else
      redirect_to user_path , notice: 'ログインしてください'
    end
  end

  def destroy

  end
  private

  def user_params
    params.require(:user).permit(
      :name, :grade_code, :school_name, :phone_number, :confirmed
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.slim
- now = Time.zone.now
.page-header
  h1
    | 生徒情報編集
= form_for(@user, class: 'form-horizontal', role: 'form') do |f|
  - if @user.errors.any?
    .alert.alert-danger
      ul
        - @user.errors.full_messages.each do |msg|
          li
            = msg
  .form-group
    = f.label '生徒として承認する'
    = f.check_box :confirmed,{checked: true}

  .form-group
    = f.label '学年'
    = f.select(:grade_code, Grade.all.map { |g| [g.name, g.code] }, {class: 'form-control'} )
  .form-group
    = f.label '氏名'
    = f.text_field :name, class: 'form-control',row: 10,placeholder:'船津圭佑'
  .form-group
    = f.label '学校名'
    = f.text_field :school_name, class: 'form-control',row: 10,placeholder:'加古川中学校'
  .form-group
    = f.label '電話番号'
    = f.telephone_field :school_name, class: 'form-control',row: 10, placeholder:'090-0000-0000'
  = f.submit '更新',class: 'btn btn-default', data: {disable_with:'更新しています...'}

app/views/users/index.html.erb
<div class="col-md-8">
  <h1>生徒一覧</h1>
  <hr>
  <%= paginate @user %>
  <div class="table-responsive">
    <table class="table table-hover">
      <tbody>
        <tr>
        <td>氏名</td>
        <td></td>
        <td></td>
        <td></td>
        </tr>
      <% @user.each do |e| %>


        <td><%= e.name %></td>
        <td><%= link_to '登録内容確認' , user_path(e), class:'btn btn-warning btn-sm'%></td>
        <td><%= link_to '指導情報登録',new_result_path(e), class:'btn btn-primary btn-sm' %></td>
        <td><%= link_to '過去の指導情報',result_path(e), class:'btn btn-info btn-sm' %></td>
        </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.slim
h2
  | 登録情報
hr
.panel.panel-info
  .panel-heading
    = '氏名：' + @user.name
  ul.list-group
    li.list-group-item
      = 'メール：' + @user.email
    li.list-group-item
      = '最近のログイン：' + @user.current_sign_in_at.strftime('%Y年%m月%d日 %H:%M')
  .panel-body
    |  直近の指導報告 
    hr
    - if @user.results.last
      h3
        = @user.results.last.title
      p
        = @user.results.last.content
    - else
      |  指導報告はありません 
= link_to '過去の指導情報',result_path, class:'btn btn-info'